### ISSUE TITLE
Support for Django 2.2

### ISSUE THREAD

**Issue by richardbarran** [richardbarran/django-photologue#197]
A note from the maintainer:

Photologue is not compatible with Django 2.2 at present - it uses django-sortedm2m, which is broken in Dango 2.2. [See this issue](https://github.com/gregmuellegger/django-sortedm2m/issues/130). When it's resolved then I can properly test Photologue.

**Comment by ppawlak** [comment]
Hello,

I wanted to let you know that I have fork django-sortedm2m to support Django 2.2
I have published the project on PyPI under the name _django-sorted-m2m_ , note the additional -

See my post here: https://github.com/gregmuellegger/django-sortedm2m/issues/130#issuecomment-500356860

**Comment by richardbarran** [comment]
Thanks - I am a bit concerned about the lack of activity on django-sortedm2m. I'm not too keen on switching over to django-sorted-m2m as it will make upgrades non-transparent for Photologue users (they will need to manually remove django-sortedm2m). But if the package maintainer does not respond soon, I will certainly consider the switch.

**Comment by richardbarran** [comment]
django-sortedm2m has been updated, I've released Photologue 3.10 which uses the new version.
