### ISSUE TITLE
Why was *_PAGINATE_BY removed?

### ISSUE THREAD

**Issue by iarp** [richardbarran/django-photologue#203]
I see in the changelog that *_PAGINATE_BY settings were removed from settings and I'm just curious as to why? Searching issues and PR's has no results.

**Comment by richardbarran** [comment]
As Photologue uses Class-Based Views, it's very easy to change the pagination - see the example in the docs https://django-photologue.readthedocs.io/en/stable/pages/customising/views.html

The need for a separate setting was not obvious - so I deprecated it.
