### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [richardbarran/django-photologue#223]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@domiee13) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by richardbarran** [comment]
Hi @JamieSlome - I've added a SECURITY.md as suggested.

**Comment by JamieSlome** [comment]
Thanks, @richardbarran 👍 

I just used the form, but just for reference, the report can be found here:

https://huntr.dev/bounties/cd8b71df-8e92-4f07-b60d-c58ae757f5bc/

**Comment by domiee13** [comment]
Hello @richardbarran 

Do you have any update about my report ?
